repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.2 
    hooks:
      - id: pylint
        args: ["--errors-only"]
        language: system
        exclude: migrate_data.py

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  
    hooks:
      - id: flake8
        language_version: python3.13
        additional_dependencies: []
        args: ["--max-line-length=100"]
        exclude: ^config/settings.*\.py$|settings\.py$|migrate_data.py

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["--format", "screen", "--skip", "B101"]
        language_version: python3.13
        exclude: migrate_data.py
